stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "fsa-frontend"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_VERIFY: ""
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  tags:
    - fsa-kubik
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - until docker info &>/dev/null; do sleep 2 && echo "Cakam na Docker daemon..."; done
    - export IMAGE_VERSION="${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "https://$ACR_REGISTRY"
    - docker build -t "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION" -t "$ACR_REGISTRY/$IMAGE_NAME:latest" .
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION"
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:latest"
  only:
    - main

deploy:
  stage: deploy
  tags:
    - fsa-kubik
  image: alpine/k8s:1.32.3
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fullstackacademy.sk/fsa-kubik/fsa2026-kubik-infra.git infra
    - kubectl apply -f infra/kubernetes/workload/04-app-frontend/
    - kubectl rollout restart deployment/fsa-fe -n app
    - kubectl rollout status deployment/fsa-fe -n app
  needs:
    - build
  only:
    - main
